// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Common.KeyVault.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "integration_test")]
    public partial class KeyvaultFeature : object, Xunit.IClassFixture<KeyvaultFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "integration_test"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "keyvault.feature"
#line hidden
        
        public KeyvaultFeature(KeyvaultFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "keyvault", "\tSimple calculator for adding two numbers", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="List all secrets from keyvault using user auth type")]
        [Xunit.TraitAttribute("FeatureTitle", "keyvault")]
        [Xunit.TraitAttribute("Description", "List all secrets from keyvault using user auth type")]
        [Xunit.TraitAttribute("Category", "User")]
        public async System.Threading.Tasks.Task ListAllSecretsFromKeyvaultUsingUserAuthType()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("List all secrets from keyvault using user auth type", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
     await testRunner.GivenAsync("vault auth type user", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
     await testRunner.WhenAsync("I list all secrets", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
     await testRunner.ThenAsync("I should get list of secret names", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="List all secrets from keyvault using msi auth type")]
        [Xunit.TraitAttribute("FeatureTitle", "keyvault")]
        [Xunit.TraitAttribute("Description", "List all secrets from keyvault using msi auth type")]
        [Xunit.TraitAttribute("Category", "Msi")]
        public async System.Threading.Tasks.Task ListAllSecretsFromKeyvaultUsingMsiAuthType()
        {
            string[] tagsOfScenario = new string[] {
                    "Msi"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("List all secrets from keyvault using msi auth type", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
        await testRunner.GivenAsync("vault auth type spn", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
        await testRunner.WhenAsync("I list all secrets", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
        await testRunner.ThenAsync("I should get list of secret names", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="List all secrets from keyvault using client secret auth type", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "keyvault")]
        [Xunit.TraitAttribute("Description", "List all secrets from keyvault using client secret auth type")]
        [Xunit.TraitAttribute("Category", "ClientSecret")]
        public async System.Threading.Tasks.Task ListAllSecretsFromKeyvaultUsingClientSecretAuthType()
        {
            string[] tagsOfScenario = new string[] {
                    "ClientSecret",
                    "ignore"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("List all secrets from keyvault using client secret auth type", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
        await testRunner.GivenAsync("vault auth type client secret with file \"longhorn17-status-report-api-pwd\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
        await testRunner.WhenAsync("I list all secrets", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
        await testRunner.ThenAsync("I should get list of secret names", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="List all secrets from keyvault using client certificate auth type", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "keyvault")]
        [Xunit.TraitAttribute("Description", "List all secrets from keyvault using client certificate auth type")]
        [Xunit.TraitAttribute("Category", "ClientCertificate")]
        public async System.Threading.Tasks.Task ListAllSecretsFromKeyvaultUsingClientCertificateAuthType()
        {
            string[] tagsOfScenario = new string[] {
                    "ClientCertificate",
                    "ignore"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("List all secrets from keyvault using client certificate auth type", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 27
        await testRunner.GivenAsync("vault auth type client secret with certificate \"longhorn17-status-report-api-cert" +
                        ".pem\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
        await testRunner.WhenAsync("I list all secrets", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
        await testRunner.ThenAsync("I should get list of secret names", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await KeyvaultFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await KeyvaultFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
