// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Rule.Expressions.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FunctionEvaluationFeature : object, Xunit.IClassFixture<FunctionEvaluationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Functions.feature"
#line hidden
        
        public FunctionEvaluationFeature(FunctionEvaluationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Function Evaluation", "  In order to use function in rule expression\r\n  As a developer\r\n  I want to be a" +
                    "ble to invoke built-in functions against a strongly typed object", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Check enum field is null")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "Check enum field is null")]
        public async System.Threading.Tasks.Task CheckEnumFieldIsNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Check enum field is null", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Gender\",\r\n      \"operator\": \"IsNull\"\r\n    " +
                        "}\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
  await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Check enum field is not null")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "Check enum field is not null")]
        public async System.Threading.Tasks.Task CheckEnumFieldIsNotNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Check enum field is not null", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
  await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
  await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Gender\",\r\n      \"operator\": \"NotIsNull\",\r\n" +
                        "    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
  await testRunner.ThenAsync("evaluation result should be \"false\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Check date field is not null")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "Check date field is not null")]
        public async System.Threading.Tasks.Task CheckDateFieldIsNotNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Check date field is not null", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"BirthDate\",\r\n      \"operator\": \"NotIsNull\"" +
                        "\r\n    },\r\n    {\r\n      \"left\": \"BirthDate\",\r\n      \"operator\": \"GreaterThan\",\r\n " +
                        "     \"right\": \"11/22/1943 10:52:28 PM\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Check date field is null")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "Check date field is null")]
        public async System.Threading.Tasks.Task CheckDateFieldIsNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Check date field is null", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Spouse.BirthDate\",\r\n      \"operator\": \"Not" +
                        "IsNull\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
    await testRunner.ThenAsync("evaluation result should be \"false\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get count of object array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get count of object array")]
        public async System.Threading.Tasks.Task GetCountOfObjectArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get count of object array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 72
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 73
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Count()\",\r\n      \"operator\": \"Equ" +
                        "als\",\r\n      \"right\": \"2\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get count of string array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get count of string array")]
        public async System.Threading.Tasks.Task GetCountOfStringArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get count of string array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Titles.Count()\",\r\n      \"operator\": \"Equal" +
                        "s\",\r\n      \"right\": \"2\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 101
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get count of string list")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get count of string list")]
        public async System.Threading.Tasks.Task GetCountOfStringList()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get count of string list", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 103
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Hobbies.Count()\",\r\n      \"operator\": \"Equa" +
                        "ls\",\r\n      \"right\": \"2\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get distinct count of string list")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get distinct count of string list")]
        public async System.Threading.Tasks.Task GetDistinctCountOfStringList()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get distinct count of string list", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 119
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 120
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 121
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Titles.DistinctCount()\",\r\n      \"operator\"" +
                        ": \"Equals\",\r\n      \"right\": \"2\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="select from object array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "select from object array")]
        public async System.Threading.Tasks.Task SelectFromObjectArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("select from object array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 135
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 136
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 137
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Select(FirstName)\",\r\n      \"opera" +
                        "tor\": \"AllIn\",\r\n      \"right\": \"Tiffany, Barron\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 149
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="select many from object array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "select many from object array")]
        public async System.Threading.Tasks.Task SelectManyFromObjectArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("select many from object array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 151
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 152
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 153
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.SelectMany(Hobbies)\",\r\n      \"ope" +
                        "rator\": \"AllIn\",\r\n      \"right\": \"Arts, Music, Dancing, Soccer\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 165
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="summarize from object array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "summarize from object array")]
        public async System.Threading.Tasks.Task SummarizeFromObjectArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("summarize from object array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 167
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 168
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 169
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Select(Age).Sum()\",\r\n      \"opera" +
                        "tor\": \"Equals\",\r\n      \"right\": \"40\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 181
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="summarize field from object array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "summarize field from object array")]
        public async System.Threading.Tasks.Task SummarizeFieldFromObjectArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("summarize field from object array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 183
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 184
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 185
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Sum(Age)\",\r\n      \"operator\": \"Eq" +
                        "uals\",\r\n      \"right\": \"40\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 197
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get average from array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get average from array")]
        public async System.Threading.Tasks.Task GetAverageFromArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get average from array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 199
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 200
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 201
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Select(Age).Average()\",\r\n      \"o" +
                        "perator\": \"Equals\",\r\n      \"right\": \"20\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 213
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get average with arg from object array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get average with arg from object array")]
        public async System.Threading.Tasks.Task GetAverageWithArgFromObjectArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get average with arg from object array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 215
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 216
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 217
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Average(Age)\",\r\n      \"operator\":" +
                        " \"Equals\",\r\n      \"right\": \"20\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 229
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get max from array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get max from array")]
        public async System.Threading.Tasks.Task GetMaxFromArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get max from array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 231
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 232
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 233
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Select(Age).Max()\",\r\n      \"opera" +
                        "tor\": \"Equals\",\r\n      \"right\": \"26\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 245
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get max with arg from object array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get max with arg from object array")]
        public async System.Threading.Tasks.Task GetMaxWithArgFromObjectArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get max with arg from object array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 247
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 248
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 249
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Max(Age)\",\r\n      \"operator\": \"Eq" +
                        "uals\",\r\n      \"right\": \"26\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 261
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get min from array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get min from array")]
        public async System.Threading.Tasks.Task GetMinFromArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get min from array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 263
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 264
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 265
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Select(Age).Min()\",\r\n      \"opera" +
                        "tor\": \"Equals\",\r\n      \"right\": \"14\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 277
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="get min with arg from object array")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "get min with arg from object array")]
        public async System.Threading.Tasks.Task GetMinWithArgFromObjectArray()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("get min with arg from object array", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 279
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 280
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 281
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Min(Age)\",\r\n      \"operator\": \"Eq" +
                        "uals\",\r\n      \"right\": \"14\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 293
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="use expression on both sides")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "use expression on both sides")]
        public async System.Threading.Tasks.Task UseExpressionOnBothSides()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("use expression on both sides", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 295
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 296
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 297
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Select(Age).Sum()\",\r\n      \"opera" +
                        "tor\": \"LessThan\",\r\n      \"right\": \"Age\",\r\n      \"rightSideIsExpression\": true\r\n " +
                        "   }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 310
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="select nested field")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "select nested field")]
        public async System.Threading.Tasks.Task SelectNestedField()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("select nested field", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 312
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 313
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 314
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Select(FirstName)\",\r\n      \"opera" +
                        "tor\": \"AllIn\",\r\n      \"right\": \"Tiffany,Barron\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 326
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="select nested field with function")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "select nested field with function")]
        public async System.Threading.Tasks.Task SelectNestedFieldWithFunction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("select nested field with function", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 328
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 329
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 330
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Select(Hobbies.OrderByDesc().Firs" +
                        "t())\",\r\n      \"operator\": \"AllIn\",\r\n      \"right\": \"Music,Soccer\"\r\n    }\r\n  ]\r\n}" +
                        "", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 342
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke function ago")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke function ago")]
        public async System.Threading.Tasks.Task InvokeFunctionAgo()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke function ago", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 344
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 345
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 346
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"BirthDate\",\r\n      \"operator\": \"GreaterTha" +
                        "n\",\r\n      \"right\": \"Ago(50000d)\",\r\n      \"rightSideIsExpression\": true\r\n    }\r\n" +
                        "  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 359
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke function where")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke function where")]
        public async System.Threading.Tasks.Task InvokeFunctionWhere()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke function where", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 361
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 362
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 363
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Where(FirstName, Equals, Tiffany)" +
                        ".Count()\",\r\n      \"operator\": \"Equals\",\r\n      \"right\": \"1\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 375
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke function where with contains")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke function where with contains")]
        public async System.Threading.Tasks.Task InvokeFunctionWhereWithContains()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke function where with contains", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 377
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 378
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 379
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Where(LastName, contains, \'ump\')." +
                        "Select(FirstName)\",\r\n      \"operator\": \"AllIn\",\r\n      \"right\": \"Tiffany,Barron\"" +
                        "\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 391
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke function first with arg")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke function first with arg")]
        public async System.Threading.Tasks.Task InvokeFunctionFirstWithArg()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke function first with arg", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 393
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 394
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 395
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.First(FirstName, Equals, Tiffany)" +
                        ".Age\",\r\n      \"operator\": \"GreaterThan\",\r\n      \"right\": \"25\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 407
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke function first without arg")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke function first without arg")]
        public async System.Threading.Tasks.Task InvokeFunctionFirstWithoutArg()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke function first without arg", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 409
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 410
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 411
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Hobbies.First()\",\r\n      \"operator\": \"Equa" +
                        "ls\",\r\n      \"right\": \"Golf\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 423
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke function last with arg")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke function last with arg")]
        public async System.Threading.Tasks.Task InvokeFunctionLastWithArg()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke function last with arg", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 425
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 426
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 427
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Last(FirstName, Equals, Tiffany)." +
                        "Age\",\r\n      \"operator\": \"GreaterThan\",\r\n      \"right\": \"14\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 439
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke function last without arg")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke function last without arg")]
        public async System.Threading.Tasks.Task InvokeFunctionLastWithoutArg()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke function last without arg", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 441
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 442
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 443
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Hobbies.Last()\",\r\n      \"operator\": \"In\",\r" +
                        "\n      \"right\": \"Golf,Tweeter\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 455
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke function order by")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke function order by")]
        public async System.Threading.Tasks.Task InvokeFunctionOrderBy()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke function order by", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 457
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 458
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 459
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.OrderBy(FirstName).First().FirstN" +
                        "ame\",\r\n      \"operator\": \"Equals\",\r\n      \"right\": \"Barron\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 471
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke function order by desc")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke function order by desc")]
        public async System.Threading.Tasks.Task InvokeFunctionOrderByDesc()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke function order by desc", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 473
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 474
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 475
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.OrderByDesc(FirstName).First().Fi" +
                        "rstName\",\r\n      \"operator\": \"Equals\",\r\n      \"right\": \"Tiffany\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 487
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke macro")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke macro")]
        public async System.Threading.Tasks.Task InvokeMacro()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke macro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 489
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 490
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 491
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"IsPresident()\",\r\n      \"operator\": \"Equals" +
                        "\",\r\n      \"right\": \"true\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 503
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke macro with args")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke macro with args")]
        public async System.Threading.Tasks.Task InvokeMacroWithArgs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke macro with args", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 505
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 506
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 507
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"IsAdult(18)\",\r\n      \"operator\": \"Equals\"," +
                        "\r\n      \"right\": \"true\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 519
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke sum on empty collection")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke sum on empty collection")]
        public async System.Threading.Tasks.Task InvokeSumOnEmptyCollection()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke sum on empty collection", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 521
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 522
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 523
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Where(Age,lessThan,0).Select(Age)" +
                        ".Sum()\",\r\n      \"operator\": \"Equals\",\r\n      \"right\": \"0\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 535
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke max on empty collection")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke max on empty collection")]
        public async System.Threading.Tasks.Task InvokeMaxOnEmptyCollection()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke max on empty collection", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 537
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 538
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 539
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Where(FirstName,equals,helloworld" +
                        ").Max(Age)\",\r\n      \"operator\": \"Equals\",\r\n      \"right\": \"0\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 551
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="invoke count on empty collection")]
        [Xunit.TraitAttribute("FeatureTitle", "Function Evaluation")]
        [Xunit.TraitAttribute("Description", "invoke count on empty collection")]
        public async System.Threading.Tasks.Task InvokeCountOnEmptyCollection()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("invoke count on empty collection", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 553
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 554
    await testRunner.GivenAsync("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 555
    await testRunner.WhenAsync("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"Children.Where(Age,lessThan,0).Count()\",\r\n" +
                        "      \"operator\": \"Equals\",\r\n      \"right\": \"0\"\r\n    }\r\n  ]\r\n}", ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 567
    await testRunner.ThenAsync("evaluation result should be \"true\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await FunctionEvaluationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await FunctionEvaluationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
