// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Rule.Expressions.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "unit_test")]
    public partial class OperatorEvaluationFeature : object, Xunit.IClassFixture<OperatorEvaluationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "unit_test"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Operators.feature"
#line hidden
        
        public OperatorEvaluationFeature(OperatorEvaluationFeature.FixtureData fixtureData, Rule_Expressions_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Operator Evaluation", "  In order to evaluate rules\r\n  As a developer\r\n  I want to be able to compile ru" +
                    "le expression against a strongly typed object", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with equal filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with equal filter returns true")]
        public void VerifyContextWithEqualFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with equal filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table1.AddRow(new string[] {
                            "City",
                            "Equals",
                            "Redmond"});
#line 9
    testRunner.When("I evaluate the rule expression", ((string)(null)), table1, "When ");
#line hidden
#line 12
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with number filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with number filter returns true")]
        public void VerifyContextWithNumberFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with number filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 15
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table2.AddRow(new string[] {
                            "Population",
                            "GreaterThan",
                            "100000"});
#line 16
    testRunner.When("I evaluate the rule expression", ((string)(null)), table2, "When ");
#line hidden
#line 19
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with number filter returns false")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with number filter returns false")]
        public void VerifyContextWithNumberFilterReturnsFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with number filter returns false", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table3.AddRow(new string[] {
                            "AvgIncome",
                            "LessOrEqual",
                            "100000"});
#line 23
    testRunner.When("I evaluate the rule expression", ((string)(null)), table3, "When ");
#line hidden
#line 26
    testRunner.Then("evaluation result should be \"false\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with in filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with in filter returns true")]
        public void VerifyContextWithInFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with in filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 29
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table4.AddRow(new string[] {
                            "State",
                            "In",
                            "CA,AZ,WA"});
#line 30
    testRunner.When("I evaluate the rule expression", ((string)(null)), table4, "When ");
#line hidden
#line 33
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with in filter trim white spaces returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with in filter trim white spaces returns true")]
        public void VerifyContextWithInFilterTrimWhiteSpacesReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with in filter trim white spaces returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 36
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table5.AddRow(new string[] {
                            "State",
                            "In",
                            "CA, AZ, WA, , DC"});
#line 37
    testRunner.When("I evaluate the rule expression", ((string)(null)), table5, "When ");
#line hidden
#line 40
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with in filter returns false")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with in filter returns false")]
        public void VerifyContextWithInFilterReturnsFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with in filter returns false", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 43
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table6.AddRow(new string[] {
                            "State",
                            "In",
                            "CA, AZ"});
#line 44
    testRunner.When("I evaluate the rule expression", ((string)(null)), table6, "When ");
#line hidden
#line 47
    testRunner.Then("evaluation result should be \"false\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with allin filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with allin filter returns true")]
        public void VerifyContextWithAllinFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with allin filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 50
    testRunner.Given("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table7.AddRow(new string[] {
                            "Hobbies",
                            "AllIn",
                            "Golf, Tweeter"});
#line 51
    testRunner.When("I evaluate the rule expression", ((string)(null)), table7, "When ");
#line hidden
#line 54
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with null field filter returns false")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with null field filter returns false")]
        public void VerifyContextWithNullFieldFilterReturnsFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with null field filter returns false", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 57
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table8.AddRow(new string[] {
                            "Street",
                            "Contains",
                            "Main"});
#line 58
    testRunner.When("I evaluate the rule expression", ((string)(null)), table8, "When ");
#line hidden
#line 61
    testRunner.Then("evaluation result should be \"false\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with contains filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with contains filter returns true")]
        public void VerifyContextWithContainsFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with contains filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 64
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table9.AddRow(new string[] {
                            "City",
                            "Contains",
                            "mond"});
#line 65
    testRunner.When("I evaluate the rule expression", ((string)(null)), table9, "When ");
#line hidden
#line 68
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with startswith filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with startswith filter returns true")]
        public void VerifyContextWithStartswithFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with startswith filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 71
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Operator",
                            "Value"});
                table10.AddRow(new string[] {
                            "City",
                            "Contains",
                            "Red"});
#line 72
    testRunner.When("I evaluate the rule expression", ((string)(null)), table10, "When ");
#line hidden
#line 75
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with composite filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with composite filter returns true")]
        public void VerifyContextWithCompositeFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with composite filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 78
    testRunner.Given("a context of type \"Location\" from json file \"redmond.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 79
    testRunner.When("I evaluate context with JSON filter", @"{
  ""allOf"": [
    {
      ""not"": {
        ""left"": ""Country"",
        ""operator"": ""equals"",
        ""right"": ""Canada""
      }
    },
    {
      ""left"": ""City"",
      ""operator"": ""equals"",
      ""right"": ""Redmond""
    },
    {
      ""left"": ""State"",
      ""operator"": ""equals"",
      ""right"": ""WA""
    }
  ]
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 103
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with nested filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with nested filter returns true")]
        public void VerifyContextWithNestedFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with nested filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 106
    testRunner.Given("an array of type \"Person\" from json file \"big_family.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 107
    testRunner.When("I evaluate context with JSON filter", @"{
  ""allOf"": [
    {
      ""left"": ""LastName"",
      ""operator"": ""Equals"",
      ""right"": ""Smith""
    },
    {
      ""not"": {
        ""anyOf"": [
          {
            ""allOf"": [
              {
                ""left"": ""FirstName"",
                ""operator"": ""In"",
                ""right"": ""Mary""
              },
              {
                ""left"": ""LastName"",
                ""operator"": ""Equals"",
                ""right"": ""Smith""
              }
            ]
          },
          {
            ""allOf"": [
              {
                ""left"": ""FirstName"",
                ""operator"": ""Equals"",
                ""right"": ""Patricia""
              },
              {
                ""left"": ""LastName"",
                ""operator"": ""Equals"",
                ""right"": ""Smith""
              }
            ]
          },
          {
            ""anyOf"": [
              {
                ""left"": ""FirstName"",
                ""operator"": ""Equals"",
                ""right"": ""Linda""
              },
              {
                ""left"": ""FirstName"",
                ""operator"": ""Equals"",
                ""right"": ""Jennifer""
              },
              {
                ""left"": ""FirstName"",
                ""operator"": ""Equals"",
                ""right"": ""Margaret""
              }
            ]
          }
        ]
      }
    }
  ]
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName"});
                table11.AddRow(new string[] {
                            "James"});
                table11.AddRow(new string[] {
                            "John"});
                table11.AddRow(new string[] {
                            "Robert"});
                table11.AddRow(new string[] {
                            "William"});
                table11.AddRow(new string[] {
                            "David"});
#line 172
    testRunner.Then("collection evaluation result should be", ((string)(null)), table11, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with nested properties returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with nested properties returns true")]
        public void VerifyContextWithNestedPropertiesReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with nested properties returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 180
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 181
    testRunner.Given("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 182
    testRunner.When("I evaluate context with JSON filter", @"{
  ""allOf"": [
    {
      ""left"": ""FirstName"",
      ""operator"": ""Equals"",
      ""right"": ""Donald""
    },
    {
      ""left"": ""LastName"",
      ""operator"": ""Equals"",
      ""right"": ""Trump""
    },
    {
      ""left"": ""Spouse.FirstName"",
      ""operator"": ""Equals"",
      ""right"": ""Melania""
    }
  ]
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 204
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with array contains filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with array contains filter returns true")]
        public void VerifyContextWithArrayContainsFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with array contains filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 206
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 207
    testRunner.Given("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 208
    testRunner.When("I evaluate context with JSON filter", @"{
  ""allOf"": [
    {
      ""left"": ""FirstName"",
      ""operator"": ""Equals"",
      ""right"": ""Donald""
    },
    {
      ""left"": ""Hobbies"",
      ""operator"": ""Contains"",
      ""right"": ""Golf""
    },
    {
      ""left"": ""Spouse.FirstName"",
      ""operator"": ""NotEquals"",
      ""right"": ""Ivanka""
    }
  ]
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 230
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with indexed array filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with indexed array filter returns true")]
        public void VerifyContextWithIndexedArrayFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with indexed array filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 232
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 233
    testRunner.Given("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 234
    testRunner.When("I evaluate context with JSON filter", @"{
  ""allOf"": [
    {
      ""left"": ""FirstName"",
      ""operator"": ""Equals"",
      ""right"": ""Donald""
    },
    {
      ""left"": ""Hobbies"",
      ""operator"": ""Contains"",
      ""right"": ""Golf""
    },
    {
      ""left"": ""Spouse.FirstName"",
      ""operator"": ""StartsWith"",
      ""right"": ""Mel""
    },
    {
      ""left"": ""Children[0].FirstName"",
      ""operator"": ""Equals"",
      ""right"": ""Tiffany""
    },
    {
      ""left"": ""Titles[1]"",
      ""operator"": ""NotEquals"",
      ""right"": ""Scientist""
    }
  ]
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 266
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with enum field in filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with enum field in filter returns true")]
        public void VerifyContextWithEnumFieldInFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with enum field in filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 268
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 269
    testRunner.Given("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 270
    testRunner.When("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"FirstName\",\r\n      \"operator\": \"Equals\",\r\n" +
                        "      \"right\": \"Donald\"\r\n    },\r\n    {\r\n      \"left\": \"Race\",\r\n      \"operator\":" +
                        " \"In\",\r\n      \"right\": \"Black,White\"\r\n    }\r\n  ]\r\n}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 287
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with date field filter returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with date field filter returns true")]
        public void VerifyContextWithDateFieldFilterReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with date field filter returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 289
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 290
    testRunner.Given("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 291
    testRunner.When("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"FirstName\",\r\n      \"operator\": \"Equals\",\r\n" +
                        "      \"right\": \"Donald\"\r\n    },\r\n    {\r\n      \"left\": \"BirthDate\",\r\n      \"opera" +
                        "tor\": \"LessThan\",\r\n      \"right\": \"2020-04-07T15:47:54.760654-07:00\"\r\n    }\r\n  ]" +
                        "\r\n}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 308
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with expression on each side returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with expression on each side returns true")]
        public void VerifyContextWithExpressionOnEachSideReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with expression on each side returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 310
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 311
    testRunner.Given("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 312
    testRunner.When("I evaluate context with JSON filter", @"{
  ""allOf"": [
    {
      ""left"": ""Children[0].LastName"",
      ""operator"": ""Equals"",
      ""right"": ""Children[1].LastName"",
      ""rightSideIsExpression"": true
    },
    {
      ""left"": ""Children.Count()"",
      ""operator"": ""Equals"",
      ""right"": ""2""
    }
  ]
}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 330
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with match operator returns true")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with match operator returns true")]
        public void VerifyContextWithMatchOperatorReturnsTrue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with match operator returns true", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 332
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 333
    testRunner.Given("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 334
    testRunner.When("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"FirstName\",\r\n      \"operator\": \"Matches\",\r" +
                        "\n      \"right\": \"^do[\\\\w]+d$\"\r\n    }\r\n  ]\r\n}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 346
    testRunner.Then("evaluation result should be \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify context with match operator returns false")]
        [Xunit.TraitAttribute("FeatureTitle", "Operator Evaluation")]
        [Xunit.TraitAttribute("Description", "Verify context with match operator returns false")]
        public void VerifyContextWithMatchOperatorReturnsFalse()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify context with match operator returns false", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 348
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 349
    testRunner.Given("a context of type \"Person\" from json file \"donald_trump.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 350
    testRunner.When("I evaluate context with JSON filter", "{\r\n  \"allOf\": [\r\n    {\r\n      \"left\": \"LastName\",\r\n      \"operator\": \"Matches\",\r\n" +
                        "      \"right\": \"^DO[\\\\w]+d$\"\r\n    }\r\n  ]\r\n}", ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 362
    testRunner.Then("evaluation result should be \"false\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                OperatorEvaluationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                OperatorEvaluationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
